### ISSUE TITLE
RandomWords stopped working

### ISSUE THREAD

**Issue by bryand23** [vaibhavsingh97/random-word#14]
I had some functioning code that used RandomWords, and it started throwing the error below out of the blue.

I tried copying the sample code directly from the documentation, and I got the same error.

`from random_word import RandomWords`
`r = RandomWords()`
```Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/Users/bryandelerson/PycharmProjects/meraki/venv/lib/python3.7/site-packages/random_word/random_word.py", line 24, in __init__
    self.issue_url)
TypeError: exceptions must derive from BaseException

**Comment by bryand23** [comment]
Oh, it looks like this is the same error as the apikey issue that's already reported - disregard.
