### ISSUE TITLE
setup.py install bug

### ISSUE THREAD

**Issue by justinkterry** [vaibhavsingh97/random-word#18]
See error below:

```
justinkterry@patternsearch:~/random-word$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import random_word
  File "/home/justinkterry/random-word/random_word/__init__.py", line 1, in <module>
    from .random_word import RandomWords
  File "/home/justinkterry/random-word/random_word/random_word.py", line 4, in <module>
    from . import config
ImportError: cannot import name 'config'
```

**Comment by vaibhavsingh97** [comment]
Hi 👋 @justinkterry. Thanks for stopping by and creating an issue 🙏🏻
You have to first add your API key in `config.py`. For your ref: https://github.com/vaibhavsingh97/random-word/blob/master/README.md#development
